<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-28 at 23:02:10.
 */
class AppHelperTest extends /*PHPUnit_Framework_TestCase*/ CTestCase {



    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
      
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }


    /**
     * @covers AppHelper::declOfNum
     * @todo   Implement testDeclOfNum().
     */
    public function testDeclOfNum() {
    
        $res = AppHelper::declOfNum(10, "рубля", "рубля", "рублей");
        
        $this->assertEquals($res, "рублей");
        
    }

}
